
const tilesInfos = [
        { "title": "Bleu sombre", "colorCode": "131625" },
        { "title": "?", "colorCode": "182235" },
        { "title": "?", "colorCode": "1e293d" },
        { "title": "?", "colorCode": "343d4c" },				   
        { "title": "Bleu-mauve \"osa\"", "colorCode": "293151" },
        { "title": "Bleu moyen", "colorCode": "4B5173" },
        { "title": "Bleu foncé", "colorCode": "091D34" },
        { "title": "Vert sombre", "colorCode": "074E46" },
        { "title": "Vert moyen", "colorCode": "0F665E" },
        { "title": "Vert clair", "colorCode": "44A59C" },
        { "title": "Rougeatre", "colorCode": "4a1b20" },
        { "title": "Red", "colorCode": "6b1c23" },
        { "title": "red saru eyes", "colorCode": "974042" },
        { "title": "violet","colorCode":"9a6fb1"},
        { "title": "Turquoise", "colorCode": "3bc5c4" },
        { "title": "Dofus - Tenue1", "colorCode": "717053" },
        { "title": "Dofus - Tenue2", "colorCode": "313124" },
        { "title": "Dofus - Cheveux", "colorCode": "c38725" },
        { "title": "Dofus - Peau", "colorCode": "f5b95f" },
        { "title": "Gold", "colorCode": "FFD700" },
        { "title": "\"cream\" Gold", "colorCode": "e1c564" },
        { "title": "Beige", "colorCode": "F7F2D4" },
        { "title": "offwhite", "colorCode": "E2F0F0" },
        { "title": "skin_flat", "colorCode": "f9e4d6" },
        { "title": "?", "colorCode": "460960"},
        { "title": "?", "colorCode": "236AB9" },
        { "title": "?", "colorCode": "C9C2EB" },
        { "title": "?", "colorCode": "BE70A9" },
        { "title": "?", "colorCode": "685E86" },
        { "title": "?", "colorCode": "6A3179" },
        { "title": "Ensemble2", "colorCode": "553949" },
        { "title": "Ensemble2", "colorCode": "294C5F" },
        { "title": "Ensemble2", "colorCode": "7F6E57" },
        { "title": "Ensemble2", "colorCode": "36404A" },
        { "title": "Ensemble2 - Peau", "colorCode": "BBB7C4" },
        { "title": "", "colorCode": "BBB7C4" },
        { "title": "", "colorCode": "4A263C" },
        { "title": "", "colorCode": "2A3356" }
    ];
export default tilesInfos;
